### ISSUE TITLE
Change terms used in README

### ISSUE THREAD

**Issue by cyanisaac** [applebetasissupercool/Fucc#2]
According to GeoSn0w, who is a security expert in the iOS security, "blobs" (currently bolbs) are actually supposed to be called "bloobs" which can be seen from the name of his tool here: https://twitter.com/FCE365/status/866387568924995584

I believe that we should update our terminology accordingly so that we keep our project looking neat and professional.

I'd like to get this moving, so permission to get started on this change would be much appreciated. If I get permission for the go-ahead, I'll make the change and submit a PR.

Let's get this moving 👍

**Comment by AppleBetas** [comment]
I think this is a great idea. 👍

**Comment by cyanisaac** [comment]
Cool, I will go ahead and assign myself and get to work on implementing it 😄

**Comment by cyanisaac** [comment]
Resolved in https://github.com/applebetasissupercool/Fucc/pull/3
